name: genezio workflow
on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: Genez-io/genezio-github-action@main
        with:
          token: ${{ secrets.GENEZIO_TOKEN }}
      - name: Build frontend
        working-directory: ./
        run: npm install && npm run build
      - name: Deploy frontend
        working-directory: ./
        run: genezio deploy --frontend
        env:
          CI: false